#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

./vendor/bin/phpstan
if [ $? -ne 0 ]; then
    echo "Larastan: Static analyse fail. Fix to continue.";
    exit 1;
fi;

php artisan test --parallel | php
if [ $? -ne 0 ]; then
    echo "PHPUnit: Test Fail. Fix to continue.";
    exit 1;
fi;

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

for FILE in $STAGED_FILES
do
    ./vendor/bin/pint "${FILE}" > /dev/null >&1;
    git add "${FILE}";
done;

exit 0;